### ISSUE TITLE
Can i use CI flash messges with slice ? 

### ISSUE THREAD

**Issue by amitpatil321** [GustMartins/Slice-Library#2]
Previously i used xiaoler/blade blade library with codeignitor and found that i cant use flash messages with it, is it possible to use codeignitor flash messages with slice ? Secondly, does slice provide all the features that blade provides so i can use it in my next CI project ?

**Comment by GustMartins** [comment]
For now, Slice **doesn't** support CodeIgniter Flash Messages! 
**But that is a great idea!**

Unfortunately, not all features provided by [Blade](https://laravel.com/docs/5.4/blade) is available in Slice. Things you **cannot** do with Slice:

+ Use [components and slots](https://laravel.com/docs/5.4/blade#components-and-slots)
+ Display unescaped data
+ Use the `@verbatim` directive
+ Use the `@isset` and `@empty` directives alone (but you **can** use the `@empty` with `@forelse()` or `@foreach()`
+ Use the loop variable
+ Render views for collections
+ Use [stacks](https://laravel.com/docs/5.4/blade#stacks)
+ Use [service injection](https://laravel.com/docs/5.4/blade#service-injection)

OMG!! I I had not realized there was so much left to do!! 
Well I'm supposed to start working right now!

**Comment by amitpatil321** [comment]
I was quite sure that flashmessages will not support, so though to ask you as a question so you can find some solution upfront. Because other libs dont support it. So far its great, best luck.

**Comment by GustMartins** [comment]
Three new directives were add in the version **1.1**: `@isset`, `@empty` and `@each`.

Can you elaborate more how could Slice-Library use CI flashdata?

One more thing... if you allow me to ask:
In your opinion, since Slice-Library deals with views (html, basically) is it a good idea that Slice-Library autoload [**Form Helper**](https://codeigniter.com/user_guide/helpers/form_helper.html) and/or [**HTML Helper**](https://codeigniter.com/user_guide/helpers/html_helper.html)?

Thank you very much!
